name: Generate Podcast Feeds
on: [push]   # So whenever something is pushed onto the main branch, it'll automatically execute this action
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3    # Version 3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |     # The pipe means "multi-line command"
          python -m pip install --upgrade pip    # Here, you put whatever you would type into the terminal
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          
